name: analytics
description: analytics
version: 1.0.0

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  utils: any

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  flutter_lints: ^3.0.0
