name: sample_clean_app

packages:
  - packages/log
  - packages/engineer_menu
  - packages/feature_flags
  - packages/router
  - packages/utils
  - packages/analytics/analytics_impl
  - packages/analytics/analytics
  - packages/uikit
  - packages/validation_forms

  - features/feature_auth
  - features/feature_main_screen
  - features/feature_inbox
  - features/feature_notifications
  - features/packages/auth_provider1

  - apps/app1
  - apps/app2

command:
  bootstrap:
    dependencies:
      flutter_bloc: ^8.1.3
      rxdart: ^0.27.7
      equatable: ^2.0.5
      formz: ^0.6.0
      build_runner: ^2.4.8
      go_router: ^12.1.1
      cupertino_icons: ^1.0.2
      watcher: ^1.1.0
      flutter_svg: ^2.0.9
      characters: ^1.0.3
      google_fonts: ^6.1.0
      get_it: ^7.6.4
      device_info_plus: ^9.1.0
      package_info_plus: 4.2.0
      collection: ^1.17.2
      logger: ^2.0.2+1
      share_plus: ^7.2.1
      path_provider: ^2.1.1
      filesystem_picker: ^4.1.0
      intl: ^0.18.1
      either_dart: any
      freezed_annotation: ^2.4.1
      json_annotation: ^4.8.1
      shared_preferences: ^2.2.2
      synchronized: ^3.1.0
      permission_handler: ^11.1.0
      uuid: ^4.2.1
      url_launcher: ^6.2.2
      dio: ^5.4.0
      provider: ^6.1.1
      freezed: ^2.4.7

      shake_gesture:
        git:
          url: https://github.com/horson/shake_gesture
          path: shake_gesture
          ref: main


    dev_dependencies:
      build_runner: ^2.4.8
      lints: ^3.0.0
      test: ^1.21.0
      flutter_gen_runner: ^5.3.2
      freezed: ^2.4.7
      json_serializable: ^6.7.1

scripts:
  analyze:
    exec: flutter analyze .
  outdated:
    exec: flutter pub outdated
  test:
    exec: flutter test

  multilizely:
    multilizely update --all-packages -g

  l10n:
    exec: flutter gen-l10n
    packageFilters:
      dependsOn: "flutter_localizations"

  build:pub_get:all:
    run: flutter pub get
    exec:
      concurrency: 6
    description: Install all dependencies

  build:clean:
    run: |
      flutter clean && \
      flutter pub get
    exec:
      concurrency: 6
    description: Clean Flutter package and install dependencies

  build:codegen:
    run: flutter pub run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
      orderDependents: true
    packageFilters:
      dependsOn: "build_runner"
    description: Run code generation using build_runner in a specific package


  build:build-apk-dev-app:
    exec: flutter build apk --build-number=$GITHUB_RUN_NUMBER --release -t lib/main_dev.dart
    description: Build dev app
    packageFilters:
      scope: "app1"

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.10.0 <4.0.0"
