name: feature_flags
description: A Flutter package to manage feature flagging.
version: 0.1.4
homepage: https://github.com/aloisdeniel/feature_flags

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  collection: ^1.17.2
  shared_preferences: ^2.2.2
  rxdart: ^0.27.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: