name: app1
description: sample clean arch app1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.5+7

environment:
  sdk: '>=3.1.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.5

  feature_auth: any
  feature_main_screen: any
  feature_inbox: any
  feature_notifications: any

  router: any
  utils: any
  analytics: any
  analytics_impl: any
  uikit: any
  feature_flags: any
  auth_provider1: any

  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7
  equatable: ^2.0.5
  go_router: ^12.1.1
  engineer_menu: any
  log: any
  get_it: ^7.6.4
  collection: ^1.17.2

#TODO: [akuznetsov] FIXME
  shake_gesture:
    git:
      url: https://github.com/horson/shake_gesture
      ref: main
      path: shake_gesture

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-BoldItalic.ttf
          weight: 700
          style: italic
