name: auth_provider1
description: sample auth data-level implementation package
version: 1.0.0

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  feature_auth: any
  either_dart: any
  log: any
  rxdart: ^0.27.7


dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  flutter_lints: ^3.0.0


