name: router
description: Router stuff for sample app
version: 1.0.0

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^12.1.1


dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  flutter_lints: ^3.0.0
