name: uikit
description: FAQTrip UIKit
version: 1.0.0

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter
  utils: any
  either_dart: any
  flutter_svg: ^2.0.9
  characters: ^1.0.3
  watcher: ^1.1.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  octo_image: ^2.0.0
  shimmer: ^3.0.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  lorem_ipsum: ^0.0.3
  equatable: ^2.0.5
  scrollable_clean_calendar: ^1.4.1
  collection: ^1.17.2
  easy_sticky_header: ^1.1.0



dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.3.2





flutter:
  assets:
    - graphics/icons/general/S/chevron/
    - graphics/icons/general/XS/
    - graphics/icons/menu/M/
    - graphics/icons/menu/M/inbox/
    - graphics/icons/menu/M/notification/
    - graphics/avatars/bottom_navigation/










flutter_gen:
  output: lib/src/ui/res
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
  assets:
    outputs:
      package_parameter_enabled: true