name: feature_auth
description: Feature Auth
version: 1.0.0

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7
  equatable: ^2.0.5
  formz: ^0.6.0
  uikit: any
  engineer_menu: any
  log: any
  router: any
  utils: any
  analytics: any
  validation_forms: any

  either_dart: any
  shared_preferences: ^2.2.2


dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  flutter_lints: ^3.0.0

