name: utils
description: utility stuff for sample app
version: 1.0.0

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.2
  url_launcher: ^6.2.2
  intl: ^0.18.1
  feature_flags: any

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  flutter_lints: ^3.0.0
