name: build_android

on: 
  workflow_dispatch:
  release:
    types: [published]

env:
  FLUTTER_VERSION: 3.19.2

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract version from tag
        if: github.ref_type == 'tag'
        uses: damienaicheh/extract-version-from-tag-action@v1.1.0 

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: 'stable'
          cache: true
          
      - name: ⚙️ Setup Melos
        uses: bluefireteam/melos-action@v2
      - run: melos run build:pub_get:all

      - if: github.ref_type == 'branch'
        run: melos run build:build-apk-dev-app

      - if: github.ref_type == 'tag'
        run: melos run build:build-apk-release-app

      - uses: actions/upload-artifact@master
        with:
          name: apk-release
          path: apps/planner/build/app/outputs/flutter-apk/app-release.apk

